# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: requests.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0erequests.proto\"`\n\x0bTestRequest\x12\x0e\n\x06\x66ield1\x18\x01 \x01(\x05\x12\x0e\n\x06\x66ield2\x18\x02 \x01(\t\x12\x0e\n\x06\x66ield3\x18\x03 \x03(\x05\x12!\n\x06\x66ield8\x18\x08 \x01(\x0b\x32\x11.SubRequestfield8\"\"\n\x10SubRequestfield8\x12\x0e\n\x06\x66ield1\x18\x01 \x01(\x05\x62\x06proto3')



_TESTREQUEST = DESCRIPTOR.message_types_by_name['TestRequest']
_SUBREQUESTFIELD8 = DESCRIPTOR.message_types_by_name['SubRequestfield8']
TestRequest = _reflection.GeneratedProtocolMessageType('TestRequest', (_message.Message,), {
  'DESCRIPTOR' : _TESTREQUEST,
  '__module__' : 'requests_pb2'
  # @@protoc_insertion_point(class_scope:TestRequest)
  })
_sym_db.RegisterMessage(TestRequest)

SubRequestfield8 = _reflection.GeneratedProtocolMessageType('SubRequestfield8', (_message.Message,), {
  'DESCRIPTOR' : _SUBREQUESTFIELD8,
  '__module__' : 'requests_pb2'
  # @@protoc_insertion_point(class_scope:SubRequestfield8)
  })
_sym_db.RegisterMessage(SubRequestfield8)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TESTREQUEST._serialized_start=18
  _TESTREQUEST._serialized_end=114
  _SUBREQUESTFIELD8._serialized_start=116
  _SUBREQUESTFIELD8._serialized_end=150
# @@protoc_insertion_point(module_scope)
