# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: response.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eresponse.proto\"9\n\x07Reponse\x12\x0e\n\x06\x66ield1\x18\x01 \x01(\x05\x12\x0e\n\x06\x66ield2\x18\x02 \x01(\t\x12\x0e\n\x06\x66ield3\x18\x03 \x01(\tb\x06proto3')



_REPONSE = DESCRIPTOR.message_types_by_name['Reponse']
Reponse = _reflection.GeneratedProtocolMessageType('Reponse', (_message.Message,), {
  'DESCRIPTOR' : _REPONSE,
  '__module__' : 'response_pb2'
  # @@protoc_insertion_point(class_scope:Reponse)
  })
_sym_db.RegisterMessage(Reponse)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REPONSE._serialized_start=18
  _REPONSE._serialized_end=75
# @@protoc_insertion_point(module_scope)
