# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: server_response.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15server_response.proto\"\xf0\x02\n\x08Response\x12\x13\n\x0bresult_code\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x10\n\x08int_list\x18\x03 \x03(\x05\x12\x13\n\x0bstring_list\x18\x04 \x03(\t\x12\x14\n\x0c\x66loat_number\x18\x05 \x01(\x02\x12\x15\n\rdouble_number\x18\x06 \x01(\x01\x12\x12\n\nis_success\x18\x07 \x01(\x08\x12&\n\x0enested_message\x18\x08 \x01(\x0b\x32\x0e.NestedMessage\x12/\n\x17repeated_nested_message\x18\t \x03(\x0b\x32\x0e.NestedMessage\x12,\n\nstring_map\x18\n \x03(\x0b\x32\x18.Response.StringMapEntry\x12\x1d\n\nenum_field\x18\x0b \x01(\x0e\x32\t.EnumType\x1a\x30\n\x0eStringMapEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\":\n\rNestedMessage\x12\x12\n\nnested_int\x18\x01 \x01(\x05\x12\x15\n\rnested_string\x18\x02 \x01(\t*A\n\x08\x45numType\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0c\n\x08OPTION_A\x10\x01\x12\x0c\n\x08OPTION_B\x10\x02\x12\x0c\n\x08OPTION_C\x10\x03\x62\x06proto3')

_ENUMTYPE = DESCRIPTOR.enum_types_by_name['EnumType']
EnumType = enum_type_wrapper.EnumTypeWrapper(_ENUMTYPE)
UNKNOWN = 0
OPTION_A = 1
OPTION_B = 2
OPTION_C = 3


_RESPONSE = DESCRIPTOR.message_types_by_name['Response']
_RESPONSE_STRINGMAPENTRY = _RESPONSE.nested_types_by_name['StringMapEntry']
_NESTEDMESSAGE = DESCRIPTOR.message_types_by_name['NestedMessage']
Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), {

  'StringMapEntry' : _reflection.GeneratedProtocolMessageType('StringMapEntry', (_message.Message,), {
    'DESCRIPTOR' : _RESPONSE_STRINGMAPENTRY,
    '__module__' : 'server_response_pb2'
    # @@protoc_insertion_point(class_scope:Response.StringMapEntry)
    })
  ,
  'DESCRIPTOR' : _RESPONSE,
  '__module__' : 'server_response_pb2'
  # @@protoc_insertion_point(class_scope:Response)
  })
_sym_db.RegisterMessage(Response)
_sym_db.RegisterMessage(Response.StringMapEntry)

NestedMessage = _reflection.GeneratedProtocolMessageType('NestedMessage', (_message.Message,), {
  'DESCRIPTOR' : _NESTEDMESSAGE,
  '__module__' : 'server_response_pb2'
  # @@protoc_insertion_point(class_scope:NestedMessage)
  })
_sym_db.RegisterMessage(NestedMessage)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _RESPONSE_STRINGMAPENTRY._options = None
  _RESPONSE_STRINGMAPENTRY._serialized_options = b'8\001'
  _ENUMTYPE._serialized_start=456
  _ENUMTYPE._serialized_end=521
  _RESPONSE._serialized_start=26
  _RESPONSE._serialized_end=394
  _RESPONSE_STRINGMAPENTRY._serialized_start=346
  _RESPONSE_STRINGMAPENTRY._serialized_end=394
  _NESTEDMESSAGE._serialized_start=396
  _NESTEDMESSAGE._serialized_end=454
# @@protoc_insertion_point(module_scope)
